FROM python:3.10-slim-buster

#inside Container
#make a new folder inside container
WORKDIR /backend-flask

#Outside container -> Inside container
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

#outside container -> Inside container
# , meanes everything in current direactiry
# first perid 
COPY . .

ENV FLASK_ENV=development

EXPOSE ${PORT}
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]